server:
  port: 8080

spring:
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:mysql://localhost:3306/jamddo?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  properties:
    hibernate:
      format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher